[general]
  network = "testnet"

[consensus]
  consensustimeout = 20
  throttlemilli = 7000
  keysfile = "/opt/dusk/conf/consensus.keys"

[database]
  dir = "/opt/dusk/data/chain/"
  driver = "heavy_v0.1.0"

[gql]
  address = "127.0.0.1:9500"
  enabled = "true"
  network = "tcp"

[gql.notification]
  brokersNum = 1
  clientsPerBroker = 1000

[logger]
  output = "stdout"
  level = "info"
  format = "json"
[logger.monitor]
enabled = false

[mempool]
  maxinvitems = "10000"
  maxsizemb = "100"
  pooltype = "diskpool"
  prealloctxs = "100"
  propagateTimeout = "100ms"
  propagateBurst = 1
  diskpoolDir = "/opt/dusk/data/chain/mempool.db"

[mempool.updates]
disabled = false
numNodes = 3

[state]
persistEvery = 100
blockGasLimit = 3000000000

[network]
  # full node service flag
  serviceFlag = 1

[rpc]
  [rpc.rusk]
    address = "127.0.0.1:8585"
    contracttimeout = 18000
    defaulttimeout = 1000
    network = "tcp"
    connectiontimeout = 5000

[api]
  enabled=false
  enableTLS = false
  address="127.0.0.1:9490"
  dbfile="/opt/dusk/data/chain/api.db"
  #5 mins
  expirationtime=300

# Kadcast peer settings
[kadcast]
# if disabled, gossip protocol is active
enabled=true

# grpc client connection config
[kadcast.grpc]
network="tcp"
address="127.0.0.1:8585"
# Number of seconds to wait for client conn establishment
dialTimeout = 10

# Timeout cfg for rpcBus calls
[timeout]
  timeoutgetmempooltxsbysize = 4
  timeoutgetmempooltxs = 3
