# log_level = 'info'
# log_type = 'coloured'
kadcast_test = false

[chain]
generation_timeout = '5s'
db_path = '/opt/dusk/rusk'
consensus_keys_path = '/opt/dusk/conf/consensus.keys'
migration_height = 438000

[databroker]
max_inv_entries = 100
max_ongoing_requests = 1000

[kadcast]
kadcast_id = 0x30
public_address = 'N/A'
listen_address = 'N/A'
bootstrapping_nodes = [
    '161.35.202.116:9000',
    '164.92.111.253:9000',
    '152.42.208.88:9000',
    '165.232.86.130:9000',
    '164.92.161.230:9000',
    '157.245.241.121:9000',
    '134.209.33.94:9000',
    '64.23.220.141:9000',
    '178.128.51.187:9000',
    '161.35.95.128:9000',
    '164.90.173.236:9000',
]
auto_propagate = false
channel_size = 1000
recursive_discovery = true

[kadcast.bucket]
node_ttl = '30s'
node_evict_after = '5s'
bucket_ttl = '1h'

[kadcast.network]
udp_recv_buffer_size = 5000000
# udp_send_backoff_timeout = '50us'
udp_send_retry_interval = '5ms'
udp_send_retry_count = 3
blocklist_refresh_interval = '10s'

[kadcast.fec.encoder]
min_repair_packets_per_block = 2
mtu = 1300
fec_redundancy = 0.15

[kadcast.fec.decoder]
cache_ttl = '1m'
cache_prune_every = '5m'
