# log_level = 'info'
# log_type = 'coloured'
kadcast_test = false

[chain]
genesis_timestamp = ''
generation_timeout = '5s'
db_path = '/opt/dusk/rusk'
consensus_keys_path = '/opt/dusk/conf/consensus.keys'

[databroker]
max_inv_entries = 100
max_ongoing_requests = 1000

[kadcast]
kadcast_id = 0x0
public_address = 'N/A'
listen_address = 'N/A'
bootstrapping_nodes = []
auto_propagate = false
channel_size = 1000
recursive_discovery = true

[kadcast.bucket]
node_ttl = '30s'
node_evict_after = '5s'
bucket_ttl = '1h'

[kadcast.network]
udp_recv_buffer_size = 5000000
# udp_send_backoff_timeout = '50us'
udp_send_retry_interval = '5ms'
udp_send_retry_count = 3
blocklist_refresh_interval = '10s'

[kadcast.fec.encoder]
min_repair_packets_per_block = 2
mtu = 1300
fec_redundancy = 0.15

[kadcast.fec.decoder]
cache_ttl = '1m'
cache_prune_every = '5m'
