# log_level = 'info'
# log_type = 'coloured'
kadcast_test = false

[chain]
db_path = '/opt/dusk/rusk'
consensus_keys_path = '/opt/dusk/conf/consensus.keys'
migration_height = 438000

[databroker]
max_inv_entries = 100
max_ongoing_requests = 1000

[kadcast]
kadcast_id = 0x20
public_address = 'N/A'
listen_address = 'N/A' 
bootstrapping_nodes = ['bootstrap1.testnet.dusk.network:9000', 'bootstrap2.testnet.dusk.network:9000', '161.35.230.6:9000', '167.71.208.74:9000', '128.199.62.50:9000', '134.122.113.239:9000', '165.227.67.186:9000', '157.230.41.115:9000', '206.189.44.83:9000', '24.199.119.91:9000']
auto_propagate = false
channel_size = 1000
recursive_discovery = true

[kadcast.bucket]
node_ttl = '30s'
node_evict_after = '5s'
bucket_ttl = '1h'

[kadcast.network]
udp_recv_buffer_size = 5000000
# udp_send_backoff_timeout = '50us'
udp_send_retry_interval = '5ms'
udp_send_retry_count = 3
blocklist_refresh_interval = '10s'

[kadcast.fec.encoder]
min_repair_packets_per_block = 2
mtu = 1300
fec_redundancy = 0.15

[kadcast.fec.decoder]
cache_ttl = '1m'
cache_prune_every = '5m'
